export const FETCH_NOTIFICATIONS = 'owner/FETCH_NOTIFICATIONS';
export const FETCH_NOTIFICATIONS_SUCCESS = 'owner/FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAILURE = 'owner/FETCH_NOTIFICATIONS_FAILURE';
