export const FETCH_REPORT = 'progress/FETCH_REPORT';
export const FETCH_REPORT_SUCCESS = 'progress/FETCH_REPORT_SUCCESS';
export const FETCH_REPORT_FAILURE = 'progress/FETCH_REPORT_FAILURE';

export const FETCH_INPUT = 'progress/FETCH_INPUT';
export const FETCH_INPUT_SUCCESS = 'progress/FETCH_INPUT_SUCCESS';
export const FETCH_INPUT_FAILURE = 'progress/FETCH_INPUT_FAILURE';

export const FETCH_OUTPUT = 'progress/FETCH_OUTPUT';
export const FETCH_OUTPUT_SUCCESS = 'progress/FETCH_OUTPUT_SUCCESS';
export const FETCH_OUTPUT_FAILURE = 'progress/FETCH_OUTPUT_FAILURE';


export const FETCH_PRODUCTIVITY = 'progress/FETCH_PRODUCTIVITY';
export const FETCH_PRODUCTIVITY_SUCCESS = 'progress/FETCH_PRODUCTIVITY_SUCCESS';
export const FETCH_PRODUCTIVITY_FAILURE = 'progress/FETCH_PRODUCTIVITY_FAILURE';


export const FETCH_SUMMARY = 'progress/FETCH_SUMMARY';
export const FETCH_SUMMARY_SUCCESS = 'progress/FETCH_SUMMARY_SUCCESS';
export const FETCH_SUMMARY_FAILURE = 'progress/FETCH_SUMMARY_FAILURE';
